name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Tina Admin (or use local schema if Cloud not ready)
        run: |
          # Try to build with Tina Cloud first
          if npm run build:tina; then
            echo "✅ Tina Cloud build succeeded"
          else
            echo "⚠️  Tina Cloud build failed - this is OK if:"
            echo "   - You just added the branch to Tina Cloud (wait ~5 minutes for indexing)"
            echo "   - You don't have Tina Cloud configured yet"
            echo ""
            echo "📝 The site will still build and deploy successfully."
            echo "   Admin will work once Tina Cloud has indexed the branch."
          fi
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}

      - name: Build site
        run: npm run build:local
        env:
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
